title: Steve Martin

logo: logo.png

description: Using economics and data science to measure the economy.

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

email: marberts@protonmail.com
